# Generated by Django 5.0.2 on 2024-03-20 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_user_confirmation_password_data_delete_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirmation_password',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chat.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
