# Generated by Django 5.0.2 on 2024-03-20 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0003_remove_user_confirmation_password_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
    ]
